// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
     
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm3Zt9GlU3yWAxXA3OAJf0i4vvJi6EeTI',
    appId: '1:739591056554:web:77e7936e460d5647cc34d3',
    messagingSenderId: '739591056554',
    projectId: 'aloulou-chatbot',
    authDomain: 'aloulou-chatbot.firebaseapp.com',
    storageBucket: 'aloulou-chatbot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM8hfWPvyHViD91KmqGrfSLzLH3cHW0t8',
    appId: '1:739591056554:android:26229a2b13294f5ccc34d3',
    messagingSenderId: '739591056554',
    projectId: 'aloulou-chatbot',
    storageBucket: 'aloulou-chatbot.firebasestorage.app',
  );

  
}