// File: data/models/chat_session.dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:uuid/uuid.dart';
import 'chat_message.dart';

class ChatSession {
  final String id;
  final String title;
  final String userId;
  final DateTime createdAt;
  final DateTime updatedAt;
  final List<ChatMessage> messages;
  final String? summary;
  final Map<String, dynamic>? metadata;
  final bool isActive;

  ChatSession({
    String? id,
    String? title,
    required this.userId,
    DateTime? createdAt,
    DateTime? updatedAt,
    List<ChatMessage>? messages,
    this.summary,
    this.metadata,
    this.isActive = true,
  }) : id = id ?? const Uuid().v4(),
       title = title ?? _generateTitle(messages),
       createdAt = createdAt ?? DateTime.now(),
       updatedAt = updatedAt ?? DateTime.now(),
       messages = messages ?? [];

  // Generate a smart title based on messages or timestamp
  static String _generateTitle([List<ChatMessage>? messages]) {
    if (messages != null && messages.isNotEmpty) {
      // Chercher le premier message utilisateur significatif
      final firstUserMessage = messages
          .where((msg) => msg.isUser && msg.text.trim().isNotEmpty)
          .firstOrNull;
      
      if (firstUserMessage != null) {
        return _createSmartTitle(firstUserMessage.text);
      }
    }
    
    // Fallback vers un titre temporel amélioré
    return _generateDefaultTitle();
  }

  // Create a smart title from message content
  static String _createSmartTitle(String text) {
    // Nettoyer le texte - garder lettres, espaces, tirets, apostrophes et accents
    String cleaned = text
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();

    if (cleaned.isEmpty) return _generateDefaultTitle();

    // Supprimer les mots vides courants du début
    final stopWords = [
      'comment', 'peux', 'tu', 'pourrais', 'voudrais', 'aimerais', 'penses',
      'que', 'qui', 'quoi', 'où', 'quand', 'pourquoi', 'est-ce', 'est', 'ce',
      'le', 'la', 'les', 'un', 'une', 'des', 'du', 'de', 'et', 'ou', 'mais',
      'salut', 'bonjour', 'bonsoir', 'hello', 'hey', 'hi'
    ];
    
    final words = cleaned.toLowerCase().split(' ');
    int startIndex = 0;
    
    // Trouver le premier mot significatif
    while (startIndex < words.length && 
           (stopWords.contains(words[startIndex]) || words[startIndex].length < 2)) {
      startIndex++;
    }

    String title;
    if (startIndex < words.length) {
      // Reconstruire avec les mots originaux (pas en minuscule)
      final originalWords = cleaned.split(' ');
      title = originalWords.sublist(startIndex).join(' ');
    } else {
      title = cleaned;
    }

    // Raccourcir si nécessaire
    const maxLength = 45;
    if (title.length > maxLength) {
      title = title.substring(0, maxLength);
      final lastSpace = title.lastIndexOf(' ');
      if (lastSpace > maxLength ~/ 2) {
        title = title.substring(0, lastSpace);
      }
      title += '...';
    }

    // Capitaliser la première lettre
    if (title.isNotEmpty) {
      title = title[0].toUpperCase() + title.substring(1);
    }

    return title.isNotEmpty ? title : _generateDefaultTitle();
  }

  // Generate default title with better formatting
  static String _generateDefaultTitle() {
    final now = DateTime.now();
    final hour = now.hour;
    
    String period;
    if (hour < 12) {
      period = 'Matinée';
    } else if (hour < 17) {
      period = 'Après-midi';
    } else {
      period = 'Soirée';
    }
    
    return '$period du ${now.day}/${now.month}/${now.year}';
  }

  // Check if title was automatically generated (for update decisions)
  bool get hasAutoGeneratedTitle {
    // Patterns pour détecter les titres automatiques
    final autoPatterns = [
      RegExp(r'^Chat \d{1,2}/\d{1,2}/\d{4} \d{1,2}:\d{2}$'),
      RegExp(r'^(Matinée|Après-midi|Soirée) du \d{1,2}/\d{1,2}/\d{4}$'),
      RegExp(r'^Discussion du \d{1,2}/\d{1,2}/\d{4}$'),
      RegExp(r'^Nouvelle (conversation|discussion)$', caseSensitive: false),
    ];

    return autoPatterns.any((pattern) => pattern.hasMatch(title)) ||
           (metadata?['autoGeneratedTitle'] == true);
  }

  // Check if the title should be updated based on message count
  bool get shouldUpdateTitle {
    if (!hasAutoGeneratedTitle) return false;
    
    final messageCount = userMessageCount;
    
    // Mettre à jour après certains seuils de messages
    return messageCount == 1 || // Premier message
           messageCount == 3 || // Après quelques échanges
           messageCount == 8 || // Session établie
           (messageCount > 10 && messageCount % 10 == 0); // Puis tous les 10
  }

  // Update title automatically if conditions are met
  ChatSession updateTitleIfNeeded() {
    if (!shouldUpdateTitle || messages.isEmpty) return this;

    final userMessages = messages.where((msg) => msg.isUser).toList();
    if (userMessages.isEmpty) return this;

    // Utiliser le premier message significatif ou le plus récent
    final messageToAnalyze = userMessages.first;
    final newTitle = _createSmartTitle(messageToAnalyze.text);
    
    if (newTitle != title && newTitle.isNotEmpty) {
      final updatedMetadata = Map<String, dynamic>.from(metadata ?? {});
      updatedMetadata['autoGeneratedTitle'] = true;
      updatedMetadata['titleGeneratedAt'] = DateTime.now().toIso8601String();
      updatedMetadata['basedOnMessage'] = messageToAnalyze.id;
      
      return copyWith(
        title: newTitle,
        metadata: updatedMetadata,
        updatedAt: DateTime.now(),
      );
    }
    
    return this;
  }

  // Manually set a custom title
  ChatSession setCustomTitle(String newTitle) {
    final updatedMetadata = Map<String, dynamic>.from(metadata ?? {});
    updatedMetadata['customTitle'] = true;
    updatedMetadata['autoGeneratedTitle'] = false;
    updatedMetadata['titleSetAt'] = DateTime.now().toIso8601String();
    
    return copyWith(
      title: newTitle.trim(),
      metadata: updatedMetadata,
      updatedAt: DateTime.now(),
    );
  }

  // Generate multiple title suggestions
  List<String> generateTitleSuggestions() {
    if (messages.isEmpty) return [_generateDefaultTitle()];
    
    final suggestions = <String>[];
    final userMessages = messages.where((msg) => msg.isUser).take(5).toList();
    
    // Suggestion basée sur le premier message
    if (userMessages.isNotEmpty) {
      final firstTitle = _createSmartTitle(userMessages.first.text);
      if (firstTitle != title) suggestions.add(firstTitle);
    }
    
    // Suggestion basée sur les mots-clés les plus fréquents
    if (userMessages.length > 1) {
      final keywordTitle = _generateKeywordBasedTitle(userMessages);
      if (keywordTitle.isNotEmpty && !suggestions.contains(keywordTitle)) {
        suggestions.add(keywordTitle);
      }
    }
    
    // Suggestion basée sur le type de questions
    final questionTitle = _generateQuestionBasedTitle(userMessages);
    if (questionTitle.isNotEmpty && !suggestions.contains(questionTitle)) {
      suggestions.add(questionTitle);
    }
    
    // S'assurer d'avoir au moins une suggestion
    if (suggestions.isEmpty) {
      suggestions.add(_generateDefaultTitle());
    }
    
    return suggestions.take(3).toList();
  }

  // Generate title based on keywords
  static String _generateKeywordBasedTitle(List<ChatMessage> messages) {
    final text = messages.map((m) => m.text.toLowerCase()).join(' ');
    
    // Catégories de sujets avec mots-clés
    final topicKeywords = {
      'Programmation': ['code', 'programme', 'développ', 'script', 'fonction', 'algorithme', 'bug', 'erreur'],
      'Cuisine': ['recette', 'cuisine', 'cuisinier', 'plat', 'ingrédient', 'cuire', 'four'],
      'Voyage': ['voyage', 'vacances', 'destination', 'pays', 'ville', 'hôtel', 'transport'],
      'Santé': ['santé', 'médecin', 'maladie', 'symptôme', 'traitement', 'exercice'],
      'Éducation': ['cours', 'école', 'étude', 'apprendre', 'université', 'formation'],
      'Technologie': ['tech', 'ordinateur', 'software', 'app', 'digital', 'internet'],
      'Science': ['science', 'recherche', 'théorie', 'expérience', 'analyse'],
    };

    for (final entry in topicKeywords.entries) {
      if (entry.value.any((keyword) => text.contains(keyword))) {
        return 'Discussion ${entry.key}';
      }
    }

    return '';
  }

  // Generate title based on question patterns
  static String _generateQuestionBasedTitle(List<ChatMessage> messages) {
    for (final message in messages) {
      final text = message.text.toLowerCase();
      
      if (text.startsWith('comment') && (text.contains('faire') || text.contains('créer'))) {
        return 'Comment faire quelque chose';
      }
      
      if (text.contains('qu\'est-ce que') || text.contains('qu est ce que')) {
        return 'Question définition';
      }
      
      if (text.startsWith('pourquoi')) {
        return 'Question explication';
      }
      
      if (text.contains('problème') || text.contains('erreur') || text.contains('bug')) {
        return 'Résolution de problème';
      }
    }
    
    return '';
  }

  // Copy with method
  ChatSession copyWith({
    String? id,
    String? title,
    String? userId,
    DateTime? createdAt,
    DateTime? updatedAt,
    List<ChatMessage>? messages,
    String? summary,
    Map<String, dynamic>? metadata,
    bool? isActive,
  }) {
    return ChatSession(
      id: id ?? this.id,
      title: title ?? this.title,
      userId: userId ?? this.userId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      messages: messages ?? this.messages,
      summary: summary ?? this.summary,
      metadata: metadata ?? this.metadata,
      isActive: isActive ?? this.isActive,
    );
  }

  // Add message to session with automatic title update
  ChatSession addMessage(ChatMessage message, {bool autoUpdateTitle = true}) {
    final updatedMessages = List<ChatMessage>.from(messages)..add(message);
    var updatedSession = copyWith(
      messages: updatedMessages,
      updatedAt: DateTime.now(),
    );
    
    // Mettre à jour le titre automatiquement si demandé
    if (autoUpdateTitle) {
      updatedSession = updatedSession.updateTitleIfNeeded();
    }
    
    return updatedSession;
  }

  // Remove message from session
  ChatSession removeMessage(String messageId) {
    final updatedMessages = messages.where((msg) => msg.id != messageId).toList();
    return copyWith(
      messages: updatedMessages,
      updatedAt: DateTime.now(),
    );
  }

  // Get last message
  ChatMessage? get lastMessage {
    if (messages.isEmpty) return null;
    return messages.last;
  }

  // Get message count
  int get messageCount => messages.length;

  // Get user message count
  int get userMessageCount => messages.where((msg) => msg.isUser).length;

  // Get AI message count
  int get aiMessageCount => messages.where((msg) => !msg.isUser).length;

  // Check if session has messages
  bool get hasMessages => messages.isNotEmpty;

  // Get preview of conversation content
  String get conversationPreview {
    if (messages.isEmpty) return 'Aucun message';
    
    final lastUserMessage = messages
        .where((msg) => msg.isUser)
        .lastOrNull;
    
    if (lastUserMessage != null) {
      final preview = lastUserMessage.text.trim();
      return preview.length > 100 
          ? '${preview.substring(0, 100)}...'
          : preview;
    }
    
    return 'Conversation en cours...';
  }

  // Convert to JSON for Firestore
  Map<String, dynamic> toFirestoreJson() {
    return {
      'id': id,
      'title': title,
      'userId': userId,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': Timestamp.fromDate(updatedAt),
      'summary': summary,
      'metadata': metadata,
      'isActive': isActive,
      'messageCount': messageCount,
      'userMessageCount': userMessageCount,
      'lastMessageText': lastMessage?.text,
      'lastMessageTimestamp': lastMessage != null 
          ? Timestamp.fromDate(lastMessage!.timestamp)
          : null,
      'conversationPreview': conversationPreview,
    };
  }

  // Convert to JSON for local storage (Hive)
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'userId': userId,
      'createdAt': createdAt.millisecondsSinceEpoch,
      'updatedAt': updatedAt.millisecondsSinceEpoch,
      'summary': summary,
      'metadata': metadata,
      'isActive': isActive,
      'messageCount': messageCount,
      'userMessageCount': userMessageCount,
      'lastMessageText': lastMessage?.text,
      'lastMessageTimestamp': lastMessage?.timestamp.millisecondsSinceEpoch,
      'conversationPreview': conversationPreview,
    };
  }

  // Convert from JSON (used for both Firestore and local storage)
  factory ChatSession.fromJson(Map<String, dynamic> json) {
    DateTime parseTimestamp(dynamic timestamp) {
      if (timestamp is Timestamp) {
        return timestamp.toDate();
      } else if (timestamp is int) {
        return DateTime.fromMillisecondsSinceEpoch(timestamp);
      } else if (timestamp is String) {
        return DateTime.parse(timestamp);
      } else {
        return DateTime.now();
      }
    }

    return ChatSession(
      id: json['id'],
      title: json['title'],
      userId: json['userId'],
      createdAt: parseTimestamp(json['createdAt']),
      updatedAt: parseTimestamp(json['updatedAt']),
      summary: json['summary'],
      metadata: json['metadata'],
      isActive: json['isActive'] ?? true,
      messages: [], // Messages are loaded separately
    );
  }

  // Convert from Firestore DocumentSnapshot
  factory ChatSession.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return ChatSession.fromJson(data);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatSession && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() {
    return 'ChatSession{id: $id, title: $title, messageCount: $messageCount, userMessages: $userMessageCount}';
  }
}